name: flutter_template
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+27

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.1
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7

  # Google
  google_sign_in: ^5.1.0
  googleapis: ^7.0.0
  google_mobile_ads: ^2.3.0

  # architecture
  riverpod: ^2.1.0
  flutter_riverpod: ^2.1.0
  freezed: ^2.1.0
  freezed_annotation: ^2.1.0
  go_router: ^6.0.0

  # api
  json_serializable: ^6.3.1
  http: ^0.13.3
  retrofit: 3.0.1
  logger: ^1.1.0

  # database
  sqflite: ^2.0.3
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  shared_preferences: ^2.0.15

  flutter_local_notifications: ^13.0.0

  # UI
  flutter_signin_button: ^2.0.0
  intl: ^0.17.0
  flutter_platform_widgets: ^2.0.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.7
  android_intent_plus: ^3.1.5
  camera: ^0.10.2+1
  crop_your_image: ^0.7.4
  uuid: ^3.0.7
  purchases_flutter: ^4.9.0
  sign_in_with_apple: ^4.3.0
  flutter_easyloading: ^3.0.5
  receive_sharing_intent: ^1.4.5
  table_calendar: ^3.0.8
  numberpicker: ^2.1.1

dev_dependencies:
  retrofit_generator: ^4.0.3
  build_runner: ^2.1.7
  drift_dev: ^2.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_android_icon.png"

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts:
   - family: NotoSans
     fonts:
       - asset: assets/fonts/NotoSansJP-Black.otf
       - asset: assets/fonts/NotoSansJP-Bold.otf
       - asset: assets/fonts/NotoSansJP-Light.otf
       - asset: assets/fonts/NotoSansJP-Medium.otf
       - asset: assets/fonts/NotoSansJP-Regular.otf
       - asset: assets/fonts/NotoSansJP-Thin.otf
