// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOtK-hkwrbndHQRJW3HjC93eU9-flYQc',
    appId: '1:78524012547:android:3287b3db87e58012d19636',
    messagingSenderId: '78524012547',
    projectId: 'pocket-schedule-de',
    storageBucket: 'pocket-schedule-de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwP53oO8FLRnsoooqnc8C98K0UlKA268',
    appId: '1:78524012547:ios:fd9f153af902b2e7d19636',
    messagingSenderId: '78524012547',
    projectId: 'pocket-schedule-de',
    storageBucket: 'pocket-schedule-de.appspot.com',
    androidClientId: '78524012547-0k56391kpp30sbjun5rd7smd60hd8n9b.apps.googleusercontent.com',
    iosClientId: '78524012547-5t3gvhqhbvu40uhsojp8qbhsb44ihr9r.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.template.dev',
  );
}
